#ifndef _SZPI_S3_BOARD_CONFIG_H_
#define _SZPI_S3_BOARD_CONFIG_H_

#include <driver/gpio.h>
#include <driver/spi_master.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_38
#define AUDIO_I2S_GPIO_WS GPIO_NUM_13
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_14
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_12
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_45

#define AUDIO_CODEC_USE_PCA9557
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_1
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_2
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR  0x82

#define BUILTIN_LED_GPIO        GPIO_NUM_NC
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#define DISPLAY_WIDTH   320
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY true

#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_42
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT true

#define DISPLAY_SPI_HOST SPI3_HOST
#define DISPLAY_MOSI_PIN GPIO_NUM_40
#define DISPLAY_CLK_PIN GPIO_NUM_41
#define DISPLAY_DC_PIN GPIO_NUM_39
#define DISPLAY_RST_PIN GPIO_NUM_NC
#define DISPLAY_SPI_PIXEL_CLOCK_HZ (80 * 1000 * 1000)

#define SZPI_PCA9557_ADDR 0x19
#define SZPI_PCA9557_LCD_CS_BIT 0
#define SZPI_PCA9557_PA_EN_BIT 1
#define SZPI_PCA9557_DVP_PWDN_BIT 2

#endif // _SZPI_S3_BOARD_CONFIG_H_
